name: notoro
description: "A new Flutter project."

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
      sdk: flutter

  cupertino_icons: ^1.0.8
  flex_color_scheme: ^8.1.1
  flutter_bloc: ^9.1.0
  hive: ^2.2.3
  path_provider: ^2.1.5
  hive_flutter: ^1.1.0
  fl_chart: ^0.70.2
  equatable: ^2.0.7
  provider: ^6.1.4
  intl: ^0.19.0
  world_flags: ^2.1.0
  flutter_native_splash: ^2.4.4


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3
  build_runner: ^2.4.15
  hive_generator: ^2.0.1
  bloc_test: ^10.0.0
  mockito: ^5.4.5

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/
    - assets/branding/
    - assets/body_parts/
    - assets/exercises/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/branding/app_logo.png"


flutter_native_splash:
  color: "#ffffff"
  image: assets/branding/app_logo_light.png
  android_gravity: center
  ios_content_mode: scaleAspectFit

  color_dark: "#121212"
  image_dark: assets/branding/app_logo.png

  android_12:
    image: assets/branding/app_logo_light.png
    icon_background_color: "#ffffff"
    image_dark: assets/branding/app_logo.png
    icon_background_color_dark: "#121212"































